// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: internal/api/pb/shortener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ExpandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ExpandResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{4}
}

type BatchRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequestItem) Reset() {
	*x = BatchRequestItem{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequestItem) ProtoMessage() {}

func (x *BatchRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequestItem.ProtoReflect.Descriptor instead.
func (*BatchRequestItem) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *BatchRequestItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequestItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchRequestItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *BatchRequest) GetItems() []*BatchRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponseItem) Reset() {
	*x = BatchResponseItem{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponseItem) ProtoMessage() {}

func (x *BatchResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponseItem.ProtoReflect.Descriptor instead.
func (*BatchResponseItem) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResponseItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchResponseItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *BatchResponse) GetItems() []*BatchResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type URLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLItem) Reset() {
	*x = URLItem{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLItem) ProtoMessage() {}

func (x *URLItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLItem.ProtoReflect.Descriptor instead.
func (*URLItem) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *URLItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *URLItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLItem             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLsResponse) Reset() {
	*x = GetURLsResponse{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsResponse) ProtoMessage() {}

func (x *GetURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsResponse.ProtoReflect.Descriptor instead.
func (*GetURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *GetURLsResponse) GetUrls() []*URLItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsRequest) Reset() {
	*x = DeleteURLsRequest{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsRequest) ProtoMessage() {}

func (x *DeleteURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteURLsRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_internal_api_pb_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_internal_api_pb_shortener_proto protoreflect.FileDescriptor

const file_internal_api_pb_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/api/pb/shortener.proto\x12\tshortener\"\"\n" +
	"\x0eShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\x0fShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x1f\n" +
	"\rExpandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x0eExpandResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\a\n" +
	"\x05Empty\"\\\n" +
	"\x10BatchRequestItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"A\n" +
	"\fBatchRequest\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.shortener.BatchRequestItemR\x05items\"W\n" +
	"\x11BatchResponseItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"C\n" +
	"\rBatchResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.shortener.BatchResponseItemR\x05items\"b\n" +
	"\aURLItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\"9\n" +
	"\x0fGetURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shortener.URLItemR\x04urls\"2\n" +
	"\x11DeleteURLsRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\xb2\x03\n" +
	"\tShortener\x12C\n" +
	"\n" +
	"ShortenURL\x12\x19.shortener.ShortenRequest\x1a\x1a.shortener.ShortenResponse\x12A\n" +
	"\fShortenBatch\x12\x17.shortener.BatchRequest\x1a\x18.shortener.BatchResponse\x12@\n" +
	"\tExpandURL\x12\x18.shortener.ExpandRequest\x1a\x19.shortener.ExpandResponse\x12,\n" +
	"\x06PingDB\x12\x10.shortener.Empty\x1a\x10.shortener.Empty\x127\n" +
	"\aGetURLs\x12\x10.shortener.Empty\x1a\x1a.shortener.GetURLsResponse\x12<\n" +
	"\n" +
	"DeleteURLs\x12\x1c.shortener.DeleteURLsRequest\x1a\x10.shortener.Empty\x126\n" +
	"\bGetStats\x12\x10.shortener.Empty\x1a\x18.shortener.StatsResponseB/Z-github.com/grnsv/shortener/internal/api/pb;pbb\x06proto3"

var (
	file_internal_api_pb_shortener_proto_rawDescOnce sync.Once
	file_internal_api_pb_shortener_proto_rawDescData []byte
)

func file_internal_api_pb_shortener_proto_rawDescGZIP() []byte {
	file_internal_api_pb_shortener_proto_rawDescOnce.Do(func() {
		file_internal_api_pb_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_pb_shortener_proto_rawDesc), len(file_internal_api_pb_shortener_proto_rawDesc)))
	})
	return file_internal_api_pb_shortener_proto_rawDescData
}

var file_internal_api_pb_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_api_pb_shortener_proto_goTypes = []any{
	(*ShortenRequest)(nil),    // 0: shortener.ShortenRequest
	(*ShortenResponse)(nil),   // 1: shortener.ShortenResponse
	(*ExpandRequest)(nil),     // 2: shortener.ExpandRequest
	(*ExpandResponse)(nil),    // 3: shortener.ExpandResponse
	(*Empty)(nil),             // 4: shortener.Empty
	(*BatchRequestItem)(nil),  // 5: shortener.BatchRequestItem
	(*BatchRequest)(nil),      // 6: shortener.BatchRequest
	(*BatchResponseItem)(nil), // 7: shortener.BatchResponseItem
	(*BatchResponse)(nil),     // 8: shortener.BatchResponse
	(*URLItem)(nil),           // 9: shortener.URLItem
	(*GetURLsResponse)(nil),   // 10: shortener.GetURLsResponse
	(*DeleteURLsRequest)(nil), // 11: shortener.DeleteURLsRequest
	(*StatsResponse)(nil),     // 12: shortener.StatsResponse
}
var file_internal_api_pb_shortener_proto_depIdxs = []int32{
	5,  // 0: shortener.BatchRequest.items:type_name -> shortener.BatchRequestItem
	7,  // 1: shortener.BatchResponse.items:type_name -> shortener.BatchResponseItem
	9,  // 2: shortener.GetURLsResponse.urls:type_name -> shortener.URLItem
	0,  // 3: shortener.Shortener.ShortenURL:input_type -> shortener.ShortenRequest
	6,  // 4: shortener.Shortener.ShortenBatch:input_type -> shortener.BatchRequest
	2,  // 5: shortener.Shortener.ExpandURL:input_type -> shortener.ExpandRequest
	4,  // 6: shortener.Shortener.PingDB:input_type -> shortener.Empty
	4,  // 7: shortener.Shortener.GetURLs:input_type -> shortener.Empty
	11, // 8: shortener.Shortener.DeleteURLs:input_type -> shortener.DeleteURLsRequest
	4,  // 9: shortener.Shortener.GetStats:input_type -> shortener.Empty
	1,  // 10: shortener.Shortener.ShortenURL:output_type -> shortener.ShortenResponse
	8,  // 11: shortener.Shortener.ShortenBatch:output_type -> shortener.BatchResponse
	3,  // 12: shortener.Shortener.ExpandURL:output_type -> shortener.ExpandResponse
	4,  // 13: shortener.Shortener.PingDB:output_type -> shortener.Empty
	10, // 14: shortener.Shortener.GetURLs:output_type -> shortener.GetURLsResponse
	4,  // 15: shortener.Shortener.DeleteURLs:output_type -> shortener.Empty
	12, // 16: shortener.Shortener.GetStats:output_type -> shortener.StatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_pb_shortener_proto_init() }
func file_internal_api_pb_shortener_proto_init() {
	if File_internal_api_pb_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_pb_shortener_proto_rawDesc), len(file_internal_api_pb_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_pb_shortener_proto_goTypes,
		DependencyIndexes: file_internal_api_pb_shortener_proto_depIdxs,
		MessageInfos:      file_internal_api_pb_shortener_proto_msgTypes,
	}.Build()
	File_internal_api_pb_shortener_proto = out.File
	file_internal_api_pb_shortener_proto_goTypes = nil
	file_internal_api_pb_shortener_proto_depIdxs = nil
}
